### ISSUE TITLE
is Julia necessary for RTIGER runing?

### ISSUE THREAD

**Issue by isaamael** [cran/RTIGER#1]
Hi ！

i wana try your sofware, but `setupJulia( ) `is so frustrating. : ( 

Would you consider supporting conda! or Julia is not necessary?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by isaamael** [comment]
I've realized this is the wrong pos. Sorry about that.
